services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: nodo_portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: nodo_vault
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - ./vault_data:/data

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: nodo_backups
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENCRYPTION_KEY}
      - CLI_ARGS=--webservice-interface=any --webservice-password=${DUPLICATI_ADMIN_PASSWORD}
    volumes:
      - ./duplicati_config:/config
      - ./duplicati_backups:/backups
      - /root/.ssh:/root/.ssh:ro
