---
- name: Instalacion y Configuracion de Vaultwarden + Portainer + Duplicati
  hosts: gestion_server
  gather_facts: yes
  tasks:
    - name: FASE 1 - Instalar Docker y dependencias instaladas
      apt:
        name: [docker.io, docker-compose, git]
        state: present
        update_cache: yes

    - name: FASE 2 - Crear directorios de persistencia y backups
      file:
        path: "/opt/servicios/nodo-gestion-core/{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - portainer_data
        - vault_data
        - duplicati_config
        - duplicati_backups

    - name: FASE 3 - Copiar el archivo docker-compose.yml original al destino
      copy:
        src: ../docker-compose.yml
        dest: /opt/servicios/nodo-gestion-core/docker-compose.yml
        mode: '0644'

    - name: FASE 4 - Lanzar Vaultwarden + Portainer + Duplicati 
      shell: "cd /opt/servicios/nodo-gestion-core && docker compose up -d"

    - name: FASE 5 - Crear directorios de persistencia y backups
      file:
        path: "/opt/servicios/nodo-gestion-core/backups"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: FASE 6 - Crear subcarpetas internas de resguardo
      file:
        path: "/opt/servicios/nodo-gestion-core/backups/{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - portainer_files
        - vaultwarden_files
        - duplicati_files
